#!/bin/sh

. /etc/functions.sh
include /lib/config

SystemModeStatus=$(uci_get system main system_mode)

[ "$SystemModeStatus" == "1" ] && {
	ipChnageEnable=$(uci_get network general auto_ip_change)
}

defaultwan=$(uci get network.general.defaultWan)

[ "$ipChnageEnable" == "1" ]&&[ "$ACTION" == "ifup" ]&&[ "$INTERFACE" == "$defaultwan" ]&&[ "$PROTO" != "static" ]&&{
	/sbin/start_auto_ip_change	
}
