$(eval $(call PackageDir,zoneinfo,zoneinfo))
$(eval $(call PackageDir,freifunk-watchdog,freifunk-watchdog))
$(eval $(call PackageDir,freifunk-p2pblock,freifunk-p2pblock))
$(eval $(call PackageDir,freifunk-firewall,freifunk-firewall))
$(eval $(call PackageDir,olsrd-luci,olsrd-luci))
$(eval $(call PackageDir,remote-update,remote-update))
$(eval $(call PackageDir,luci,luci))
