#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

. /etc/functions.sh

config_load system
config_get city main weather_city
config_get degree main weather_degree

rm -rf /var/weather
wget "http://weather.yahooapis.com/forecastrss?p=${city}&u=${degree}" -O /var/weather &  
#killall wget
