#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

. /etc/functions.sh

START=11

start() {
	##check ucitrack type:system option:init ,led-->password
	
	sys_track=`/sbin/uci get ucitrack.@system[0].init`
	
	[ $sys_track=="led" ]&&{
		/sbin/uci set ucitrack.@system[0].init="password"
		/sbin/uci commit ucitrack
	}

	if [ -f /etc/passwd+ ]; then
		rm /etc/passwd+
	fi
	
	#protect login root id
	chk_password=$(cat /etc/passwd |grep root:)
        [ -z "$chk_password" ] && {
                echo "root::0:0:root:/:/bin/ash" >> /etc/passwd
        }

	config_load system
	config_get password main pwd
	(echo "$password"; sleep 1; echo "$password") | passwd

	if [ -f /etc/passwd+ ]; then
		rm /etc/passwd+
	fi
}
