HOST_OS:=Linux
HOST_ARCH:=i686
GNU_HOST_NAME:=i486-linux-gnu
TAR:=/bin/tar
FIND:=/home/steven/streamboost_test/trunk/staging_dir/host/bin/find
BASH:=/bin/bash
FIND_L=/home/steven/streamboost_test/trunk/staging_dir/host/bin/find -L $(1)
XARGS:=xargs -r
PATCH:=/usr/bin/patch
PYTHON:=/home/steven/streamboost_test/trunk/staging_dir/host/bin/python
