HOST_OS:=Linux
HOST_ARCH:=i686
GNU_HOST_NAME:=i486-linux-gnu
TAR:=/bin/tar
FIND:=/usr/bin/find
BASH:=/bin/bash
FIND_L=/usr/bin/find -L $(1)
XARGS:=xargs -r
PATCH:=/usr/bin/patch
PYTHON:=/usr/bin/python
