#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org
START=97

. /etc/functions.sh
include /lib/config

start() {
	uci_set wireless_macfilter general0 reset 1
        uci_set wireless_macfilter general1 reset 1
        uci_set wireless_macfilter general2 reset 1
        uci_set wireless_macfilter general3 reset 1

	uci_commit wireless_macfilter

	macfilter start
}

stop() {
	macfilter stop
}

restart() {
	macfilter restart
}

reload() {
	macfilter reload
}
