#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 1 1
proto_set_keep 1
[ -n "$PPP_IPPARAM" ] && {
	[ -n "$IPLOCAL" ] && proto_add_ipv4_address "$IPLOCAL" 32
	[ -n "$IPREMOTE" ] && { 
		proto_add_ipv4_route 0.0.0.0 0 "$IPREMOTE"

                #Sean Ling
                #for Multi-wan/interface group routing table
		if [ "$IFNAME" == "pppoe-wan" ]; then
			INTERFACE="wan"
		elif [ "$IFNAME" == "pppoe-wan1"]; then
			INTERFACE="wan1"
		elif [ "$IFNAME" == "pppoe-wan2" ]; then
			INTERFACE="wan2"
		elif [ "$IFNAME" == "pppoe-wan3" ]; then
			INTERFACE="wan3"
		elif [ "$IFNAME" == "pppoe-wan4" ]; then
			INTERFACE="wan4"
		fi
		[ -n "$INTERFACE" ] && {	
			uci set network.$INTERFACE.isp_gw=$IPREMOTE
			uci commit network
		}
	}
	[ -n "$LLLOCAL" ] && proto_add_ipv6_address "$LLLOCAL" 128
	[ -n "$DNS1" ] && proto_add_dns_server "$DNS1"
	[ -n "$DNS2" -a "$DNS1" != "$DNS2" ] && proto_add_dns_server "$DNS2"
	echo "ppp ip-up $PPP_IPPARAM " >> /tmp/121
}
proto_send_update "$PPP_IPPARAM"



[ -d /etc/ppp/ip-up.d ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}
