#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"

#Sean Ling
#for Multi-wan/interface group routing table
if [ "$IFNAME" == "pppoe-wan" ]; then
	INTERFACE="wan"
elif [ "$IFNAME" == "pppoe-wan1"]; then
	INTERFACE="wan1"
elif [ "$IFNAME" == "pppoe-wan2" ]; then
	INTERFACE="wan2"
elif [ "$IFNAME" == "pppoe-wan3" ]; then
	INTERFACE="wan3"
elif [ "$IFNAME" == "pppoe-wan4" ]; then
	INTERFACE="wan4"
fi

uci del network.$INTERFACE.isp_gw
uci commit network

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}
